### ISSUE TITLE
{:error, :unknown_connection} - why that?

### ISSUE THREAD

**Issue by solars** [gausby/tortoise#107]
Hi there,

I'm trying to set up a daemon that periodically (SchedEx) pushes to MQTT.
Somehow I'm getting {:error, :unknown_connection} if I try to send and I'm not sure what causes it, it might be the application/supervision tree.

This is the relevant code:
https://gist.github.com/solars/9a816e297840acef5011072598b9cb8d

Any idea what's wrong?

**Comment by solars** [comment]
Nevermind, my fault :/

**Comment by gausby** [comment]
Sorry I didn't respond to this; good to see you figured it out.

Perhaps I should mention this in the docs :)

I'd like to hear what you are using Tortoise for, if you are willing to share :)

**Comment by solars** [comment]
Thanks for the reply :)

We're working on platform for various IoT applications (Smart City/Agriculture/Construction Site).
Right now we still use hulakii + tortoise in parallel, but as I'm seeing a lot of errors with hulaaki I will replace it with tortoise as well.
