### ISSUE TITLE
Subscriptions are ineffective unless suffixed with "/#"

### ISSUE THREAD

**Issue by jfcloutier** [gausby/tortoise#91]
I am seeing this behavior as of v0.9.2. 

Subscriptions to specific topics, e.g. "this/or/that", no longer work. I now need to subscribe to "/this/or/that/#" to see messages with topic "this/or/that".

**Comment by jfcloutier** [comment]
In my mix.exs

`{ :tortoise, "~> 0.9" }`

mix deps.get shows

 `tortoise 0.9.2`

**Comment by gausby** [comment]
Did it work in the versions prior to v0.9.2 ?

Something to note: the topic `this/or/that` is not equal to `/this/or/that`; a handle_message that would match these would look like this:
```elixir
# this/or/that
def handle_message(["this", "or", "that"], payload, state) do
    {:ok, state}
end

# /this/or/that (notice the empty string before "this" !
def handle_message(["", "this", "or", "that"], payload, state) do
    {:ok, state}
end
```
This is one oddity in the protocol, but I guess it happens to make sense with the behavior of most *split string* functions in most programming languages.

And, as you might know: `#` will match multiple levels, so it would not make sense that `/this/or/that/#` would match `this/or/that`…because the former does not start with a forward slash. If you get messages on that topic using that subscription I have a suspicion that it could be the broker.

So:
- What broker are you using ?
- Did it ever work in tortoise; and if so, at what version number ?

I will have to go to bed soon. I will look into it tomorrow evening (Copenhagen time)

**Comment by jfcloutier** [comment]
Sorry, typo: this/or/that in both cases

We are using CloudMQTT.

We have been using Tortoise for months (much gratitude!). We had no such issue under v0.8

**Comment by gausby** [comment]
Okay; I'll head home and see if I can reproduce it…and I'll see if CloudMQTT have a free tier as well. Thanks.

**Comment by gausby** [comment]
Everything seems to work fine with one tortoise sending a message directed at a specific topic (`this/or/that`) to another tortoise running on another node via the VerneMQ broker.

I will try to see if I can get a free account on CloudMQTT and test if I can reproduce it there.

**Comment by jfcloutier** [comment]
I am working on the part of IoT hub's firmware that interacts with an MQTT broker. The problem appeared after we moved to Elixir 1.7.3 from 1.6, and upgraded to the latest Tortoise and Nerves releases. Once I worked out the kinks of that upgrade, I was surprised that the hub was no longer receiving messages for topics it registered for just as it did before (using specific topics). The code invoking Tortoise's subscribe had not changed. That was very puzzling. I found out that only by adding "/#" to each subscription topic was I able to get the hub to receive messages as before. It could very well be a change in the broker I am unaware of.

**Comment by gausby** [comment]
I just had to write their support (in defeat); I cannot seem to get a connection on my cute cat instance :-/

**Comment by jfcloutier** [comment]
I am currently experiencing connectivity issues with MQTTCloud. Could be the US Judiciary Committee Hearing that everyone here is streaming.

**Comment by gausby** [comment]
I set my instance to Ireland.

**Comment by jfcloutier** [comment]
All is well when using AWS for IoT MQTT. The problem seems to be with CloudMQTT, not Tortoise. Sorry for the false alarm. Feel free to close this issue.

**Comment by gausby** [comment]
Great to hear…or, I hope they get that issue fixed.

Perhaps I should create a server check script that could help diagnose servers.

**Comment by brianmay** [comment]
Martin Gausby <notifications@github.com> writes:

> Perhaps I should create a server check script that could help diagnose servers.

That actually sounds like a really good idea.

Something you can add to as you find more broken stuff in servers. Plus
hopefully users will be able to determine that their server is broken
before filling redundant bug reports.
-- 
Brian May <brian@linuxpenguins.xyz>
https://linuxpenguins.xyz/brian/

**Comment by gausby** [comment]
Once I've gotten the MQTT 5 stuff in I will be able to do better diagnostics, because the protocol in general is a bit more informative when stuff goes wrong. Good stuff is coming up—and my plan is to still support 3.1.1, so no worries if you are on a broker that only support that :)
